const Images = {
  logo: require('../assets/Images/logo.png'),
  welcome_1: require('../assets/Images/welcome_1.jpg'),
  welcome_2: require('../assets/Images/welcome_2.jpg'),
  banner_1: require('../assets/Images/b1.jpg'),
  banner_2: require('../assets/Images/b2.jpg'),
  banner_3: require('../assets/Images/b3.png'),
  apple: require('../assets/Images/apple.png'),
  blackberry: require('../assets/Images/blackberry.png'),
  gionee: require('../assets/Images/gionee.png'),
  htc: require('../assets/Images/htc.png'),
  karbonn: require('../assets/Images/karbonn.png'),
  lava: require('../assets/Images/lava.png'),
  lenovo: require('../assets/Images/lenovo.png'),
  lyf: require('../assets/Images/lyf.png'),
  micromax: require('../assets/Images/micromax.png'),
  motorola: require('../assets/Images/motorola.png'),
  nokia: require('../assets/Images/nokia.png'),
  oneplus: require('../assets/Images/oneplus.png'),
  oppo: require('../assets/Images/oppo.png'),
  panasonic: require('../assets/Images/panasonic.png'),
  realme: require('../assets/Images/realme.png'),
  samsung: require('../assets/Images/samsung.png'),
  vivo: require('../assets/Images/vivo.png'),
  xiaomi: require('../assets/Images/xiaomi.png'),
  xolo: require('../assets/Images/xolo.png'),
  mobile_1: require('../assets/Images/1.jpg'),
  mobile_2: require('../assets/Images/2.jpg'),
  mobile_3: require('../assets/Images/3.jpg'),
  mobile_4: require('../assets/Images/4.jpg'),
  mobile_5: require('../assets/Images/5.jpg'),
  mobile_6: require('../assets/Images/6.png'),
  mobile_7: require('../assets/Images/7.jpg'),
  mobile_8: require('../assets/Images/8.jpg'),
  mobile_9: require('../assets/Images/9.png')
};

export default Images;
