export const types = {
    //global
    TOGGLE_APP_LOADING: "TOGGLE_APP_LOADING",
    GET_PROFILE_DATA:'GET_PROFILE_DATA',
    PROFILE_REDUCER:'PROFILE_REDUCER',
    GET_CATEGORY_DATA:'GET_CATEGORY_DATA',
    CATEGORY_REDUCER:'CATEGORY_REDUCER',
    GET_BRAND_DATA:'GET_BRAND_DATA',
    BRAND_REDUCER:'BRAND_REDUCER',
  
   
}  
